# Generated by Django 3.1.6 on 2021-02-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('City_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Arabic_Name', models.CharField(max_length=200, null=True)),
                ('English_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('Nationality_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Arabic_Name', models.CharField(max_length=200, null=True)),
                ('English_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('Officer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('Specialization', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officers_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Officer_ID', models.FloatField(null=True)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=200, null=True)),
                ('Photo', models.ImageField(max_length=200, null=True, upload_to='MEDIA_ROOT/Officers/Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('Specialization_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Arabic_Name', models.CharField(max_length=200, null=True)),
                ('English_Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('Job_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Company_Name', models.CharField(max_length=100, null=True)),
                ('Salary', models.FloatField(max_length=20, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
                ('City_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities')),
                ('Nationality_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities')),
                ('Specialization_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Birth_Date', models.DateTimeField(null=True)),
                ('Photo', models.ImageField(null=True, upload_to='MEDIA_ROOT/Employees/Images/')),
                ('CV_File', models.FileField(null=True, upload_to='MEDIA_ROOT/Employees/CVs/')),
                ('City_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities')),
                ('Nationality_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities')),
                ('Specialization_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200, null=True)),
                ('Job_Title', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=2000, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_Istitution', models.CharField(max_length=200, null=True)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
                ('PDF_File', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Employees/Certificates/')),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Contact_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.FloatField(null=True)),
                ('Twitter', models.CharField(max_length=100, null=True)),
                ('Instagram', models.CharField(max_length=100, null=True)),
                ('LinkedIn', models.URLField(max_length=100, null=True)),
                ('WhatsApp', models.CharField(max_length=100, null=True)),
                ('Telegram', models.CharField(max_length=100, null=True)),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_Istitution', models.CharField(max_length=200, null=True)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Description', models.CharField(max_length=2000, null=True)),
                ('PDF_File', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Employees/Certificates/')),
                ('Employee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.employees')),
            ],
        ),
    ]
