# Generated by Django 4.2.1 on 2024-01-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('total_hours', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('second_name', models.CharField(max_length=25, null=True)),
                ('third_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_primary', models.CharField(max_length=20, null=True)),
                ('phone_secondary', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('bio', models.TextField(max_length=1000, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('degree', models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('total_hours', models.IntegerField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Educations',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('end_date', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Experiences',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('progress', models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Educations',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Experiences',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('progress', models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('second_name', models.CharField(max_length=25, null=True)),
                ('third_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_primary', models.CharField(max_length=20, null=True)),
                ('phone_secondary', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('degree', models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.IntegerField(default='0')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ES_Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('codename', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Applied',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('personal_id', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('second_name', models.CharField(max_length=25, null=True)),
                ('third_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_primary', models.CharField(max_length=20, null=True)),
                ('phone_secondary', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('degree', models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True)),
                ('cover_letter', models.CharField(max_length=2000, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\ESolutions\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='Jobs Solutions', max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date_receive', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.CharField(default='0', max_length=10, null=True)),
                ('is_trash', models.CharField(default='0', max_length=10, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Replay',
            fields=[
                ('replay_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.mail')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date_receive', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.CharField(default='0', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('arabic_name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('ministries', 'Ministries'), ('banks', 'Banks'), ('companies', 'Companies'), ('communications', 'Communications'), ('hospital', 'Hospital')], max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Phone_Interviews',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('how_heared_about_job', models.CharField(choices=[('Friend', 'Friend'), ('ES Website', 'ES Website'), ('Social Media', 'Social Media')], max_length=200, null=True)),
                ('hear_speak_problem', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('has_health_condition', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('want_to_work', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('live_in_riyadh', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('have_transportation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('call_behavior', models.CharField(choices=[('Excelent', 'Excelent'), ('Not Interested', 'Not Interested'), ('Careless', 'Careless'), ('Weak', 'Weak'), ('Playboy', 'Playboy'), ('Not Serious', 'Not Serious')], max_length=200, null=True)),
                ('future_goal', models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position'), ('Waiting for Another Profession', 'Waiting for Another Profession'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education'), ('Interested in a Government Job', 'Interested in a Government Job'), ("Doesn't Want to Disclose", "Doesn't Want to Disclose")], max_length=200, null=True)),
                ('why_this_job', models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position'), ('Waiting for Another Profession', 'Waiting for Another Profession'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education'), ('Interested in a Government Job', 'Interested in a Government Job'), ('For Marriage', 'For Marriage'), ('Develop Himself', 'Develop Himself'), ('Gain Experience', 'Gain Experience'), ('Improving the Financial Situation', 'Improving the Financial Situation')], max_length=200, null=True)),
                ('saudi_driving_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('Successed', 'Successed'), ('Failed', 'Failed')], max_length=200, null=True)),
                ('latest_update', models.DateTimeField(null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='Excelent Solutions', max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_trash', models.CharField(default='0', max_length=10, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Mail_Replay',
            fields=[
                ('replay_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.sent_mail')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_certificates',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_contact_information',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_educations',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_experiences',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='City_ID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Nationality_ID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Specialization_ID',
        ),
        migrations.DeleteModel(
            name='Officers',
        ),
        migrations.DeleteModel(
            name='Officers_Login',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='Arabic_Name',
            new_name='arabic_name',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='City_ID',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='English_Name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='City_ID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Job_ID',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Nationality_ID',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Specialization_ID',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Company_Name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='nationalities',
            old_name='Arabic_Name',
            new_name='arabic_name',
        ),
        migrations.RenameField(
            model_name='nationalities',
            old_name='English_Name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='nationalities',
            old_name='Nationality_ID',
            new_name='nationality_id',
        ),
        migrations.RenameField(
            model_name='specializations',
            old_name='Arabic_Name',
            new_name='arabic_name',
        ),
        migrations.RenameField(
            model_name='specializations',
            old_name='English_Name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='specializations',
            old_name='Specialization_ID',
            new_name='specialization_id',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Salary',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Start_Date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='Title',
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_available',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='what_we_expect_from_you',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='what_you_have_got',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Employee_Certificates',
        ),
        migrations.DeleteModel(
            name='Employee_Contact_Information',
        ),
        migrations.DeleteModel(
            name='Employee_Educations',
        ),
        migrations.DeleteModel(
            name='Employee_Experiences',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AddField(
            model_name='phone_interviews',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations'),
        ),
        migrations.AddField(
            model_name='phone_interviews',
            name='suited_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.jobs'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employment.jobs'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities'),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employment.jobs'),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities'),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations'),
        ),
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities'),
        ),
        migrations.AddField(
            model_name='clients',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities'),
        ),
        migrations.AddField(
            model_name='clients',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations'),
        ),
        migrations.AddField(
            model_name='client_skills',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_experiences',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_educations',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities'),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities'),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations'),
        ),
        migrations.AddField(
            model_name='client_courses',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='admin_permission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.es_permission'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.partners'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
