# Generated by Django 3.1.6 on 2021-02-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_Istitution', models.CharField(max_length=200, null=True)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Description', models.CharField(max_length=2000, null=True)),
                ('PDF_File', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Contact_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twitter', models.CharField(max_length=100, null=True)),
                ('Instagram', models.CharField(max_length=100, null=True)),
                ('LinkedIn', models.URLField(max_length=100, null=True)),
                ('WhatsApp', models.CharField(max_length=100, null=True)),
                ('Telegram', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_Istitution', models.CharField(max_length=200, null=True)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
                ('PDF_File', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200, null=True)),
                ('Job_Title', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=2000, null=True)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('Client_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Phone', models.FloatField(null=True)),
                ('Birth_Date', models.DateTimeField(null=True)),
                ('Photo', models.ImageField(null=True, upload_to='MEDIA_ROOT/Clients/Images/')),
                ('CV_File', models.FileField(null=True, upload_to='MEDIA_ROOT/Clients/CVs/')),
                ('City_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities')),
                ('Nationality_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.nationalities')),
                ('Specialization_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='Employees_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.FloatField(null=True)),
                ('Full_Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=200, null=True)),
                ('Photo', models.ImageField(max_length=200, null=True, upload_to='MEDIA_ROOT/Employees/Images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_certificates',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_contact_information',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_educations',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee_experiences',
            name='Employee_ID',
        ),
        migrations.DeleteModel(
            name='Officers',
        ),
        migrations.DeleteModel(
            name='Officers_Login',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Birth_Date',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='CV_File',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='City_ID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Nationality_ID',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Specialization_ID',
        ),
        migrations.AddField(
            model_name='employees',
            name='Phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='Specialization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Employee_Certificates',
        ),
        migrations.DeleteModel(
            name='Employee_Contact_Information',
        ),
        migrations.DeleteModel(
            name='Employee_Educations',
        ),
        migrations.DeleteModel(
            name='Employee_Experiences',
        ),
        migrations.AddField(
            model_name='client_experiences',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_educations',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_contact_information',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
        migrations.AddField(
            model_name='client_certificates',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients'),
        ),
    ]
