# Generated by Django 3.1.6 on 2021-02-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20210221_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Birth_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='CV_File',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
