# Generated by Django 3.1.6 on 2021-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20210222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
    ]
