# Generated by Django 3.1.6 on 2021-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0007_auto_20210222_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
