# Generated by Django 3.1.6 on 2021-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_auto_20210222_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Birth_Date',
            field=models.DateField(),
        ),
    ]
