# Generated by Django 3.1.6 on 2021-02-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_auto_20210222_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='CV_File',
            field=models.FileField(upload_to='media/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Photo',
            field=models.ImageField(null=True, upload_to='media/Clients/Images/'),
        ),
    ]
