# Generated by Django 3.1.6 on 2021-02-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0012_auto_20210223_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_experiences',
            old_name='Job_Title',
            new_name='Job_title',
        ),
        migrations.AlterField(
            model_name='client_certificates',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client_educations',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client_educations',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client_experiences',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client_experiences',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
