# Generated by Django 3.1.6 on 2021-02-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0013_auto_20210224_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Educational_Istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('Date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('total_hours', models.IntegerField(null=True)),
                ('pdf_file', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='Client_Certificates',
        ),
    ]
