# Generated by Django 3.1.6 on 2021-02-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0014_auto_20210224_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_courses',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='client_courses',
            old_name='Educational_Istitution',
            new_name='educational_istitution',
        ),
        migrations.RenameField(
            model_name='client_educations',
            old_name='Educational_Istitution',
            new_name='educational_istitution',
        ),
        migrations.RenameField(
            model_name='client_experiences',
            old_name='Job_title',
            new_name='job_title',
        ),
    ]
