# Generated by Django 3.1.6 on 2021-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0017_auto_20210226_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(max_length=1000, null=True, upload_to='MEDIA_ROOT/Clients/Images/'),
        ),
    ]
