# Generated by Django 3.1.6 on 2021-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0018_auto_20210226_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(null=True, upload_to='MEDIA_ROOT/Clients/Images/'),
        ),
    ]
