# Generated by Django 3.1.6 on 2021-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0019_auto_20210227_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_experiences',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
