# Generated by Django 3.1.6 on 2021-03-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0020_auto_20210301_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_experiences',
            old_name='id',
            new_name='experience_id',
        ),
    ]
