# Generated by Django 3.1.6 on 2021-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0021_auto_20210301_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client_educations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
