# Generated by Django 3.1.6 on 2021-03-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0022_auto_20210301_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_courses',
            old_name='id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='client_educations',
            old_name='id',
            new_name='education_id',
        ),
    ]
