# Generated by Django 3.1.6 on 2021-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0025_client_skills_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_skills',
            name='progress',
            field=models.IntegerField(choices=[('Expert', 100), ('Advanced', 80), ('Excelent', 60), ('Good', 40), ('Beigener', 20)], null=True),
        ),
    ]
