# Generated by Django 3.1.6 on 2021-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0026_auto_20210327_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_skills',
            name='progress',
            field=models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True),
        ),
    ]
