# Generated by Django 3.1.6 on 2021-03-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0027_auto_20210327_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_contact_information',
            old_name='linkedIn',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='client_contact_information',
            old_name='whatsApp',
            new_name='whatsapp',
        ),
    ]
