# Generated by Django 3.1.6 on 2021-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0028_auto_20210329_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact_information',
            name='instagram',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='linkedin',
            field=models.URLField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='telegram',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='twitter',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='whatsapp',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
