# Generated by Django 3.2 on 2021-04-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0029_auto_20210329_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_contact_information',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employees_login',
            name='id',
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='employment.clients'),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='linkedin',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='telegram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_contact_information',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees_login',
            name='employee_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
