# Generated by Django 3.2 on 2021-04-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0030_auto_20210413_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Applied',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employment.clients')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employment.jobs')),
            ],
        ),
    ]
