# Generated by Django 3.2 on 2021-04-15 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0032_job_applied_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_applied',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 16, 12, 23, 396062)),
        ),
    ]
