# Generated by Django 3.2 on 2021-04-15 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0033_auto_20210415_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 17, 39, 41, 806110)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
