# Generated by Django 3.2 on 2021-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0036_alter_jobs_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
