# Generated by Django 3.2 on 2021-04-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0039_client_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_cv',
            old_name='client_id',
            new_name='client',
        ),
    ]
