# Generated by Django 3.2 on 2021-04-28 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0040_rename_client_id_client_cv_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_CV_Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('progress', models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Experiences',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Educations',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('pdf_file', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client_CV_Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('educational_istitution', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('total_hours', models.IntegerField(null=True)),
                ('pdf_file', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
