# Generated by Django 3.2 on 2021-04-28 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0041_client_cv_courses_client_cv_educations_client_cv_experiences_client_cv_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
