# Generated by Django 3.2 on 2021-04-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0043_alter_client_cv_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_active',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
