# Generated by Django 3.2 on 2021-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0044_auto_20210430_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applied',
            name='bio',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
