# Generated by Django 3.2 on 2021-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0045_job_applied_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_applied',
            name='bio',
        ),
        migrations.AddField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(default='', upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
