# Generated by Django 3.2 on 2021-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0046_auto_20210502_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
