# Generated by Django 3.2 on 2021-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0049_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date_receive',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
