# Generated by Django 3.2 on 2021-05-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0051_auto_20210503_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employment.jobs'),
        ),
    ]
