# Generated by Django 3.2 on 2021-05-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0054_alter_mail_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='receiver',
        ),
    ]
