# Generated by Django 3.2 on 2021-05-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0056_mail_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='is_read',
            field=models.CharField(default=False, max_length=10, null=True),
        ),
    ]
