# Generated by Django 3.2 on 2021-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0057_alter_mail_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('arabic_name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('logo', models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/')),
            ],
        ),
    ]
