# Generated by Django 3.2 on 2021-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0059_auto_20210520_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='is_read',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
