# Generated by Django 3.2 on 2021-05-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0060_alter_mail_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='Excelent Solutions', max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_trashed', models.CharField(default='0', max_length=10, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
