# Generated by Django 3.2 on 2021-06-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0061_sent_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Interviews',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('how_heared_about_job', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('hear_speak_problem', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('sick', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('want_to_work', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('live_in_riyadh', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('have_transportation', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('call_behavior', models.CharField(choices=[('Excelent', 'Excelent - ممتاز'), ('Not Interested', 'Not Interested - غير مهتم'), ('Careless', 'Careless - غير مبالي'), ('Weak', 'Weak - ضعيف'), ('Playboy', 'Playboy - مستهتر'), ('Not Serious', 'Not Serious - غير جاد')], max_length=200, null=True)),
                ('future_goal', models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position - يبحث عن منصب إداري'), ('Waiting for Another Profession', 'Waiting for Another Profession - ينتظر مهنة أخرى'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education - متطلع للتعليم العالي'), ('Interested in a Government Job', 'Interested in a Government Job - مهتم بوظيفة حكومية'), ("Doesn't Want to Disclose", "Doesn't Want to Disclose - لا يرغب بالإفصاح")], max_length=200, null=True)),
                ('why_this_job', models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position - يبحث عن منصب إداري'), ('Waiting for Another Profession', 'Waiting for Another Profession - ينتظر مهنة أخرى'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education - متطلع للتعليم العالي'), ('Interested in a Government Job', 'Interested in a Government Job - مهتم بوظيفة حكومية'), ('For Marriage', 'For Marriage - الزواج'), ('Develop Himself', 'Develop Himself - تطوير نفسه'), ('Gain Experience', 'Gain Experience - إكتساب خبرة'), ('Improving the Financial Situation', 'Improving the Financial Situation - تحسين الوضع المالي')], max_length=200, null=True)),
                ('saudi_driving_license', models.CharField(choices=[('Yes', 'Yes - نعم'), ('No', 'No - لا')], max_length=200, null=True)),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
