# Generated by Django 3.2 on 2021-06-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0063_rename_call_interviews_phone_interviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone_interviews',
            old_name='sick',
            new_name='has_health_condition',
        ),
    ]
