# Generated by Django 3.2 on 2021-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0066_alter_phone_interviews_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cv',
            name='degree',
            field=models.CharField(choices=[('Intermediate School', 'Intermediate School - المرحلة الإبتدائية'), ('High School', 'High School - المرحلة الثانوية'), ('Deploma', 'Deploma - دبلوم'), ("Bachelor's Degree", "Bachelor's Degree - بكلاريوس"), ("Master's Degree", "Master's Degree - ماجستير"), ("PHD's Degree", "PHD's Degree - دكتوراه")], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='degree',
            field=models.CharField(choices=[('Intermediate School', 'Intermediate School - المرحلة الإبتدائية'), ('High School', 'High School - المرحلة الثانوية'), ('Deploma', 'Deploma - دبلوم'), ("Bachelor's Degree", "Bachelor's Degree - بكلاريوس"), ("Master's Degree", "Master's Degree - ماجستير"), ("PHD's Degree", "PHD's Degree - دكتوراه")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male - ذكر'), ('Female', 'Female - أنثى')], max_length=200, null=True),
        ),
    ]
