# Generated by Django 3.2 on 2021-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0067_auto_20210613_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_interviews',
            name='latest_update',
            field=models.DateTimeField(null=True),
        ),
    ]
