# Generated by Django 3.2 on 2021-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0068_phone_interviews_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
