# Generated by Django 3.2 on 2021-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0071_alter_clients_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='clients',
            name='phone2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
