# Generated by Django 3.2 on 2021-06-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0072_auto_20210615_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='phone1',
            new_name='phone_primary',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='phone2',
            new_name='phone_secondary',
        ),
    ]
