# Generated by Django 3.2 on 2021-06-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0073_auto_20210615_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_cv',
            old_name='phone1',
            new_name='phone_primary',
        ),
        migrations.RenameField(
            model_name='client_cv',
            old_name='phone2',
            new_name='phone_secondary',
        ),
    ]
