# Generated by Django 3.2 on 2021-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0075_auto_20210617_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_skills',
            name='progress',
            field=models.IntegerField(choices=[(100, 'Expert (100%) خبير'), (80, 'Advanced (80%) متقدم'), (60, 'Excelent (60%) ممتاز'), (40, 'Good (40%) جيد'), (20, 'Beigener (20%) مبتدئ')], null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male - ذكر'), ('Female', 'Female - أنثى')], max_length=200, null=True),
        ),
    ]
