# Generated by Django 3.2 on 2021-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0076_auto_20210617_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cv',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='second_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client_cv',
            name='third_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='client_cv_skills',
            name='progress',
            field=models.IntegerField(choices=[(100, 'Expert (100%) خبير'), (80, 'Advanced (80%) متقدم'), (60, 'Excelent (60%) ممتاز'), (40, 'Good (40%) جيد'), (20, 'Beigener (20%) مبتدئ')], null=True),
        ),
    ]
