# Generated by Django 3.2 on 2021-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0077_auto_20210619_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cv',
            name='personal_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
