# Generated by Django 3.2 on 2021-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0079_alter_client_cv_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='personal_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
