# Generated by Django 3.2 on 2021-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0081_auto_20210619_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='personal_id',
            field=models.CharField(default='0123456789', max_length=10, unique=True),
        ),
    ]
