# Generated by Django 4.0 on 2021-12-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0083_alter_clients_personal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sent_mail',
            old_name='is_trashed',
            new_name='is_trash',
        ),
    ]
