# Generated by Django 4.0 on 2021-12-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0084_rename_is_trashed_sent_mail_is_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='is_trashed',
            new_name='is_trash',
        ),
    ]
