# Generated by Django 4.0 on 2021-12-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0085_rename_is_trashed_mail_is_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
