# Generated by Django 4.0 on 2021-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0099_alter_job_applied_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='personal_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
