# Generated by Django 4.0 on 2021-12-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0100_alter_client_cv_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='personal_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
