# Generated by Django 4.0 on 2021-12-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employment', '0101_alter_client_cv_personal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_applied',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='email',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='phone_primary',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='third_name',
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='photo',
            field=models.ImageField(null=True, upload_to='MEDIA_ROOT/Clients/Images/'),
        ),
        migrations.AlterField(
            model_name='client_cv_educations',
            name='pdf_file',
            field=models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
