# Generated by Django 4.0 on 2021-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0105_job_applied_birth_date_job_applied_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='photo',
            field=models.ImageField(null=True, upload_to='MEDIA_ROOT/Clients/Images/'),
        ),
        migrations.AlterField(
            model_name='client_cv_educations',
            name='pdf_file',
            field=models.FileField(max_length=2000, null=True, upload_to='MEDIA_ROOT/Clients/Certificates/'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='personal_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
