# Generated by Django 4.0 on 2021-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0106_alter_client_cv_cv_file_alter_client_cv_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(null=True, upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
