# Generated by Django 4.0 on 2021-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0107_alter_job_applied_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='MEDIA_ROOT/Clients/CVs/'),
        ),
    ]
