# Generated by Django 4.0 on 2021-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0109_alter_job_applied_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='cv_file',
            field=models.FileField(upload_to='C:\\Users\\Mohammed Elgaily\\Django\\ES\\static/media/Clients/CVs/'),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='photo',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Mohammed Elgaily\\Django\\ES\\static/media/Clients/Images/'),
        ),
        migrations.AlterField(
            model_name='client_cv_educations',
            name='pdf_file',
            field=models.FileField(max_length=2000, null=True, upload_to='C:\\Users\\Mohammed Elgaily\\Django\\ES\\static/media/Clients/Certificates/'),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='personal_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
