# Generated by Django 4.0 on 2021-12-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0110_alter_client_cv_cv_file_alter_client_cv_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='personal_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
