# Generated by Django 4.0 on 2021-12-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0111_alter_job_applied_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cv_educations',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
