# Generated by Django 4.0 on 2021-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0112_client_cv_educations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
