# Generated by Django 4.0 on 2021-12-28 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employment', '0113_partners_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('date_receive', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.CharField(default='0', max_length=10, null=True)),
                ('is_trash', models.CharField(default='0', max_length=10, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
