# Generated by Django 4.0 on 2021-12-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0114_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_trash',
        ),
    ]
