# Generated by Django 4.0 on 2021-12-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0115_remove_notification_is_trash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
