# Generated by Django 4.0 on 2021-12-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0117_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='what_we_expect_from_you',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='what_you_have_got',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
