# Generated by Django 4.0 on 2021-12-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0118_jobs_requirements_jobs_what_we_expect_from_you_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.partners'),
        ),
    ]
