# Generated by Django 4.0 on 2021-12-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0121_remove_jobs_company_name_jobs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
        migrations.AddField(
            model_name='partners',
            name='category',
            field=models.CharField(choices=[('ministries', 'ministries'), ('banks', 'Banks'), ('companies', 'companies'), ('communications', 'communications'), ('hospital', 'hospital')], max_length=200, null=True),
        ),
    ]
