# Generated by Django 4.0 on 2021-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0122_remove_jobs_category_partners_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='category',
            field=models.CharField(choices=[('ministries', 'Ministries'), ('banks', 'Banks'), ('companies', 'Companies'), ('communications', 'Communications'), ('hospital', 'Hospital')], max_length=200, null=True),
        ),
    ]
