# Generated by Django 4.0 on 2022-01-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0123_alter_partners_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Mohammed Elgaily\\Django\\ES\\static/media'),
        ),
    ]
