# Generated by Django 4.0 on 2022-01-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0139_alter_client_cv_cv_file_alter_client_cv_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
