# Generated by Django 4.0 on 2022-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0141_alter_client_cv_cv_file_alter_client_cv_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, default='static/ProfilePage/images/avatar.jpg', null=True, upload_to=''),
        ),
    ]
