# Generated by Django 4.0 on 2022-01-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0142_alter_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_cv',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to=''),
        ),
    ]
