# Generated by Django 4.0 on 2022-01-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0144_alter_client_cv_photo_alter_clients_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_cv',
            name='cv_file',
        ),
    ]
