# Generated by Django 4.0 on 2022-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0145_remove_client_cv_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cv',
            name='cv_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\Mohammed Elgaily\\Django\\ES\\media/Clients/CVs/'),
        ),
    ]
