# Generated by Django 4.0 on 2022-01-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0150_alter_mail_replay_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_replay',
            old_name='date_receive',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sent_mail_replay',
            old_name='date_sent',
            new_name='date',
        ),
    ]
