# Generated by Django 4.0 on 2022-01-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employment', '0151_rename_date_receive_mail_replay_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applied',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
