# Generated by Django 4.0 on 2022-01-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employment', '0153_alter_job_applied_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard', models.IntegerField(default='0')),
                ('mail_read', models.IntegerField(default='0')),
                ('mail_write', models.IntegerField(default='0')),
                ('client_read', models.IntegerField(default='0')),
                ('client_write', models.IntegerField(default='0')),
                ('job_read', models.IntegerField(default='0')),
                ('job_write', models.IntegerField(default='0')),
                ('phone_interview_read', models.IntegerField(default='0')),
                ('phone_interview_write', models.IntegerField(default='0')),
                ('partner_read', models.IntegerField(default='0')),
                ('partner_write', models.IntegerField(default='0')),
                ('admin_read', models.IntegerField(default='0')),
                ('admin_write', models.IntegerField(default='0')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
