# Generated by Django 4.0 on 2022-01-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0154_admin_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ES_Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='admin_permission',
            old_name='permission_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='admin_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='admin_write',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='client_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='client_write',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='job_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='job_write',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='mail_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='mail_write',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='partner_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='partner_write',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='phone_interview_read',
        ),
        migrations.RemoveField(
            model_name='admin_permission',
            name='phone_interview_write',
        ),
        migrations.AddField(
            model_name='admin_permission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employment.es_permission'),
        ),
    ]
