# Generated by Django 4.0 on 2022-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0155_es_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='es_permission',
            name='codename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
