# Generated by Django 4.0 on 2022-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0156_es_permission_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_available',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
    ]
