# Generated by Django 4.0 on 2022-01-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0157_jobs_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_courses',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='client_cv',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='client_cv_courses',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='client_cv_educations',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='client_educations',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='cv_file',
        ),
    ]
