# Generated by Django 4.2.1 on 2024-01-15 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0160_client_cv_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_applied',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job_applied',
            name='specialization',
        ),
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='cover_letter',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='degree',
            field=models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_cv',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_cv_skills',
            name='progress',
            field=models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True),
        ),
        migrations.AlterField(
            model_name='client_skills',
            name='progress',
            field=models.IntegerField(choices=[(100, 'Expert (100%)'), (80, 'Advanced (80%)'), (60, 'Excelent (60%)'), (40, 'Good (40%)'), (20, 'Beigener (20%)')], null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='degree',
            field=models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='degree',
            field=models.CharField(choices=[('Intermediate School', 'Intermediate School'), ('High School', 'High School'), ('Deploma', 'Deploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ("PHD's Degree", "PHD's Degree")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='what_we_expect_from_you',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='what_you_have_got',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(default='Jobs Solutions', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='call_behavior',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Not Interested', 'Not Interested'), ('Careless', 'Careless'), ('Weak', 'Weak'), ('Playboy', 'Playboy'), ('Not Serious', 'Not Serious')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='future_goal',
            field=models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position'), ('Waiting for Another Profession', 'Waiting for Another Profession'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education'), ('Interested in a Government Job', 'Interested in a Government Job'), ("Doesn't Want to Disclose", "Doesn't Want to Disclose")], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='has_health_condition',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='have_transportation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='hear_speak_problem',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='how_heared_about_job',
            field=models.CharField(choices=[('Friend', 'Friend'), ('ES Website', 'ES Website'), ('Social Media', 'Social Media')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='live_in_riyadh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='result',
            field=models.CharField(choices=[('Successed', 'Successed'), ('Failed', 'Failed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='saudi_driving_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='want_to_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phone_interviews',
            name='why_this_job',
            field=models.CharField(choices=[('Seeking for Administration Position', 'Seeking for Administration Position'), ('Waiting for Another Profession', 'Waiting for Another Profession'), ('Looking Forward to Higher Education', 'Looking Forward to Higher Education'), ('Interested in a Government Job', 'Interested in a Government Job'), ('For Marriage', 'For Marriage'), ('Develop Himself', 'Develop Himself'), ('Gain Experience', 'Gain Experience'), ('Improving the Financial Situation', 'Improving the Financial Situation')], max_length=200, null=True),
        ),
    ]
