# Generated by Django 4.2.1 on 2024-01-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0161_remove_job_applied_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applied',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.cities'),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\ESolutions\\media/Clients/CVs/'),
        ),
        migrations.AddField(
            model_name='job_applied',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.specializations'),
        ),
    ]
