# Generated by Django 4.2.1 on 2024-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0162_job_applied_city_job_applied_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent_mail_replay',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='job_applied',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\ESolutions\\media'),
        ),
    ]
