# Generated by Django 4.2.1 on 2024-01-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0163_sent_mail_replay_is_admin_alter_job_applied_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_replay',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
